// 前端路由配置
const routerConfig = {
  // 主路由路径
  paths: {
    index: '/index',
    home: 'home',
    center: 'center',
    pay: 'pay',
    storeup: 'storeup',
    news: 'news',
    newsDetail: 'newsDetail',
    yonghu: 'yonghu',
    yonghuDetail: 'yonghuDetail',
    yonghuAdd: 'yonghuAdd',
    historyinfo: 'historyinfo',
    historyinfoDetail: 'historyinfoDetail',
    historyinfoAdd: 'historyinfoAdd',
    topten: 'topten',
    toptenDetail: 'toptenDetail',
    toptenAdd: 'toptenAdd',
    gupiaoxinxi: 'gupiaoxinxi',
    gupiaoxinxiDetail: 'gupiaoxinxiDetail',
    gupiaoxinxiAdd: 'gupiaoxinxiAdd',
    gupiaoleixing: 'gupiaoleixing',
    gupiaoleixingDetail: 'gupiaoleixingDetail',
    gupiaoleixingAdd: 'gupiaoleixingAdd',
    gupiaojiaoyi: 'gupiaojiaoyi',
    gupiaojiaoyiDetail: 'gupiaojiaoyiDetail',
    gupiaojiaoyiAdd: 'gupiaojiaoyiAdd',
    newstype: 'newstype',
    newstypeDetail: 'newstypeDetail',
    newstypeAdd: 'newstypeAdd',
    systemintro: 'systemintro',
    systemintroDetail: 'systemintroDetail',
    systemintroAdd: 'systemintroAdd',
    login: '/login',
    register: '/register'
  },
  
  // 路由组件映射
  components: {
    Index: '../pages',
    Home: '../pages/home/home',
    Login: '../pages/login/login',
    Register: '../pages/register/register',
    Center: '../pages/center/center',
    Storeup: '../pages/storeup/list',
    News: '../pages/news/news-list',
    NewsDetail: '../pages/news/news-detail',
    payList: '../pages/pay',
    yonghuList: '../pages/yonghu/list',
    yonghuDetail: '../pages/yonghu/detail',
    yonghuAdd: '../pages/yonghu/add',
    historyinfoList: '../pages/historyinfo/list',
    historyinfoDetail: '../pages/historyinfo/detail',
    historyinfoAdd: '../pages/historyinfo/add',
    toptenList: '../pages/topten/list',
    toptenDetail: '../pages/topten/detail',
    toptenAdd: '../pages/topten/add',
    gupiaoxinxiList: '../pages/gupiaoxinxi/list',
    gupiaoxinxiDetail: '../pages/gupiaoxinxi/detail',
    gupiaoxinxiAdd: '../pages/gupiaoxinxi/add',
    gupiaoleixingList: '../pages/gupiaoleixing/list',
    gupiaoleixingDetail: '../pages/gupiaoleixing/detail',
    gupiaoleixingAdd: '../pages/gupiaoleixing/add',
    gupiaojiaoyiList: '../pages/gupiaojiaoyi/list',
    gupiaojiaoyiDetail: '../pages/gupiaojiaoyi/detail',
    gupiaojiaoyiAdd: '../pages/gupiaojiaoyi/add',
    newstypeList: '../pages/newstype/list',
    newstypeDetail: '../pages/newstype/detail',
    newstypeAdd: '../pages/newstype/add',
    systemintroList: '../pages/systemintro/list',
    systemintroDetail: '../pages/systemintro/detail',
    systemintroAdd: '../pages/systemintro/add'
  }
};

export default routerConfig;